inherit_from: configs/dual/default.yaml
training:
  out_dir: output/fashion/D2GAN_sup
  batch_size: 64
  log_every: 100
  gan_type: standard
  dual_alpha: 0.3
  dual_beta: 0.5
data:
  type: FashionMNIST
  train_dir: data/FashionMNIST
  img_size: 32
  nlabels: 10
generator:
  name: dcgan_shallow
  nlabels: 1
  conditioning: unconditional
  kwargs:
    placeholder: None
discriminator1:
  name: dcgan_shallow
  nlabels: 1
  conditioning: unconditional
  kwargs:
    placeholder: None
discriminator2:
  name: dcgan_shallow
  nlabels: 1
  conditioning: unconditional
  kwargs:
    placeholder: None